sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t xlldnsz/multi-docker-fibonacci-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xlldnsz/multi-docker-fibonacci-test npm test

after_success:
  - docker build -t xlldnsz/multi-docker-fibonacci-client ./client
  - docker build -t xlldnsz/multi-docker-fibonacci-nginx ./nginx
  - docker build -t xlldnsz/multi-docker-fibonacci-worker ./worker
  - docker build -t xlldnsz/multi-docker-fibonacci-server ./server
  # Login to the docker CLI with encrypted credentials generated in Travis UI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to user's docker hub
  - docker push xlldnsz/multi-docker-fibonacci-client
  - docker push xlldnsz/multi-docker-fibonacci-nginx
  - docker push xlldnsz/multi-docker-fibonacci-worker
  - docker push xlldnsz/multi-docker-fibonacci-server

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-371232125960'
  bucker_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY